// This file was generated by img2gb, DO NOT EDIT

#include <types.h>

UINT8 WINDOW_TILEMAP[] = {//13 + 7
        55, 56, 55, 56, 53, 54, 64, 64, 64, 64, 64, 64, 64, 57, 58, 59, 60, 61, 60, 63,
        67, 68, 67, 68, 65, 66, 64, 64, 64, 64, 64, 64, 64 , 69, 70, 71, 72, 71, 72, 75,
};
